apiVersion: v1
kind: Pod
metadata:
  name: teste-pod
  labels:
    app.kubernetes.io/name: teste-pod
spec:
  containers:
    - name: teste-pod
      image: rukasu/starwars-scene:v2
      ports:
        - containerPort: 80
